spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/student_db
    username: postgres
    password: 222845
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false